version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management  # Ensure you are using the management image
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port for messaging
      - "15672:15672" # Management UI port for the web interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  service1:
    image: nodal_service1
    build:
      context: nodal_service1/demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq

  service2:
    image: nodal_service2
    build:
      context: nodal_service2/demo
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq