#services:
#  rabbitmq:
#    image: 'rabbitmq:3-management'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=guest'
#      - 'RABBITMQ_DEFAULT_USER=guest'
#    ports:
#      - '5672'
#      - '15672'


version: '3.8'

services:
  service1:
    image: nodal_service1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management  # Ensure you are using the management image
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port for messaging
      - "15672:15672" # Management UI port for the web interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
